<?php
/**
* Soap client MyMoviesAPI
*
* Autogenerated with the Yii extension wsdl2php.
*/

class MyMovieBase
{
	public $UserName; //string;
	public $Password; //string;
	
	function __construct()
	{
		$this->UserName = "rdsmart";
		$this->Password = "SmartLiving01";
	}	
}

class LoadDiscTitleByIdRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $TitleId; //string;
	public $Client; //string;
	public $Version; //string;
	public $Locale; //int;
}

class LoadDiscTitleByIdResponse
{
	public $LoadDiscTitleByIdResult; //LoadDiscTitleByIdResult;
}

class LoadDiscTitleByIdResult
{
	public $any; //string;
}

class SearchDiscTitleByTitleRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $Title; //string;
	public $Country; //string;
	public $Type; //string;
	public $Results; //int;
	public $Strict; //boolean;
	public $IncludeEnglish; //boolean;
	public $IncludeAdult; //boolean;
	public $Locale; //int;
}

class SearchDiscTitleByTitleResponse
{
	public $SearchDiscTitleByTitleResult; //SearchDiscTitleByTitleResult;
}

class SearchDiscTitleByTitleResult
{
	public $any; //string;
}
	
	
	/**
	* The soap client proxy class
	*/
class MyMoviesAPI 
{
	public $soapClient;
	
	private static $classmap = array(
	
	);
	
	function __construct($url='https://api.mymovies.dk/default.asmx?WSDL')
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => false));
	}
	
	function LoadDiscTitleById($idTitle)
	{

		$modelRequest = new LoadDiscTitleByIdRequest();
		
		$modelRequest->TitleId = $idTitle; //string;
		$modelRequest->Locale = 0;
			
		$response = $this->soapClient->LoadDiscTitleById($modelRequest);
			
		if(isset($response))
			return simplexml_load_string($response->LoadDiscTitleByIdResult->any);
		
		return null;
	}
	
	
	function SearchDiscTitleByTitle($title = '', $country = '')
	{

		$modelRequest = new SearchDiscTitleByTitleRequest();
		$modelRequest->Title = $title;
		$modelRequest->Results = 10;
		$modelRequest->Strict = true;
		$modelRequest->IncludeEnglish = true;
		$modelRequest->IncludeAdult = true;
		$modelRequest->Country = $country;
		$modelRequest->Locale = 0;
		
		$response = $this->soapClient->SearchDiscTitleByTitle($modelRequest);
		
		if(isset($response))
			return simplexml_load_string($response->SearchDiscTitleByTitleResult->any);
		
		return null;
	
	}
	
}


