<?php
/**
* Soap client WsMonitor
*
* Autogenerated with the Yii extension wsdl2php.
*/


class HeartBeat
{
	public $Id_device; //string;
	public $Id_device_state; //integer;
	public $Id_device_type; //integer;
	public $description; //string;
	public $insert_date; //string;
}

/**
* The soap client proxy class
*/
class WsMonitor 
 {
	public $soapClient;
	public $token;
	
	private static $classmap = array(

		);

	function __construct()
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$model = ExternalWsdl::model()->findByAttributes(array('description'=>'Monitor'));
		$url = $model->url;
		$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
		$this->token = $this->login($model->username, $model->password);
	}


	function login($username,$password)
	{
		return $this->soapClient->login($username, $password);		
	}
	
	public function getHeartBeat()
	{
		$heartBeatArray = array();
		if(isset($this->soapClient))
		{
			$heartBeatArray = $this->soapClient->getHeartBeat($this->token);
		}
		return $heartBeatArray;
	}
	public function getHeartBeatByDeviceId($idDevice)
	{
		$heartBeatArray = array();
		if(isset($this->soapClient))
		{
			$heartBeatArray = $this->soapClient->getHeartBeatByDeviceId($this->token, $idDevice);
		}
		return $heartBeatArray;
	}
	function ackHeartBeat($arrHeartBeat)
	{
		$result = false;
		if(isset($this->soapClient))
		{
			$result = $this->soapClient->ackHeartBeat($this->token, $arrHeartBeat);
		}
		return $result;
	}
}


