<?php
/**
* Soap client MyMoviesAPI
*
* Autogenerated with the Yii extension wsdl2php.
*/

class MyMovieBase
{
	public $UserName; //string;
	public $Password; //string;
	
	function __construct()
	{
		$this->UserName = "rdsmart";
		$this->Password = "SmartLiving01";
	}	
}

class LoadDiscTitleByIMDBIdRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $IMDBId; //string;
	public $Country; //string;
	public $Type; //string;
	public $IncludeEnglish; //string;
	public $IncludeAdult; //string;
	public $Client; //string;
	public $Version; //string;
	public $Locale; //int;
}

class LoadDiscTitleByIMDBIdResponse
{
	public $LoadDiscTitleByIMDBIdResult; //LoadDiscTitleByIMDBIdResult;
}

class LoadDiscTitleByIMDBIdResult
{
	public $any; //string;
}

class LoadSeriesRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $Id; //string;
	public $LanguageCode; //string;
	public $Country; //string;
	public $Locale; //int;
}

class LoadSeriesResponse
{
	public $LoadSeriesResult; //LoadSeriesResult;
}

class LoadSeriesResult
{
	public $any; //string;
}

class LoadDiscTitleByTitleRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $Title; //string;
	public $Country; //string;
	public $Type; //string;
	public $Strict; //string;
	public $IncludeEnglish; //string;
	public $IncludeAdult; //string;
	public $Client; //string;
	public $Version; //string;
	public $Locale; //int;
}

class LoadDiscTitleByTitleResponse
{
	public $LoadDiscTitleByTitleResult; //LoadDiscTitleByTitleResult;
}

class LoadDiscTitleByTitleResult
{
	public $any; //string;
}

class LoadDiscTitleByIdRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $TitleId; //string;
	public $Client; //string;
	public $Version; //string;
	public $Locale; //int;
}

class LoadDiscTitleByIdResponse
{
	public $LoadDiscTitleByIdResult; //LoadDiscTitleByIdResult;
}

class LoadDiscTitleByIdResult
{
	public $any; //string;
}

class SearchDiscTitleByTitleRequest extends MyMovieBase
{
	public $Handshake; //string;
	public $Reference; //string;
	public $Title; //string;
	public $Country; //string;
	public $Type; //string;
	public $Results; //int;
	public $Strict; //boolean;
	public $IncludeEnglish; //boolean;
	public $IncludeAdult; //boolean;
	public $Locale; //int;
}

class SearchDiscTitleByTitleResponse
{
	public $SearchDiscTitleByTitleResult; //SearchDiscTitleByTitleResult;
}

class SearchDiscTitleByTitleResult
{
	public $any; //string;
}
	
	
	/**
	* The soap client proxy class
	*/
class MyMoviesAPI 
{
	public $soapClient;
	
	private static $classmap = array(
	
	);
	
	function __construct($url='https://api.mymovies.dk/default.asmx?WSDL')
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => false));
	}
	
	function LoadDiscTitleById($idTitle)
	{

		$modelRequest = new LoadDiscTitleByIdRequest();
		
		$modelRequest->TitleId = $idTitle; //string;
		$modelRequest->Locale = 0;
			
		$response = $this->soapClient->LoadDiscTitleById($modelRequest);
			
		if(isset($response))
			return simplexml_load_string($response->LoadDiscTitleByIdResult->any);
		
		return null;
	}
	
	function LoadDiscTitleByIMDBId($idImdb = '', $country = '')
	{
		$modelRequest = new LoadDiscTitleByIMDBIdRequest();
		
		$modelRequest->IMDBId = $idImdb; //string;
		$modelRequest->Country = $country; //string;
		$modelRequest->Type = ''; //string;
		$modelRequest->IncludeEnglish = true; //string;
		$modelRequest->IncludeAdult = true; //string;
		$modelRequest->Locale = 0;
		
		$response = $this->soapClient->LoadDiscTitleByIMDBId($modelRequest);
			
		if(isset($response))
			return simplexml_load_string($response->LoadDiscTitleByIMDBIdResult->any);
		
		return null;
	}
	
	function LoadDiscTitleByTitle($title = '', $country = '')
	{
	
		$modelRequest = new LoadDiscTitleByIdRequest();
	
		$modelRequest->Title = $title; //string;
		$modelRequest->Country = $country; //string;
		$modelRequest->Type = ''; //string;
		$modelRequest->Strict = true; //string;
		$modelRequest->IncludeEnglish = true; //string;
		$modelRequest->IncludeAdult = true; //string;
		$modelRequest->Locale = 0;

		$response = $this->soapClient->LoadDiscTitleByTitle($modelRequest);
			
		if(isset($response))
			return simplexml_load_string($response->LoadDiscTitleByTitleResult->any);
	
		return null;
	}
	
	function LoadSeries($idSerie, $country = '')
	{
		$modelRequest = new LoadSeriesRequest();
		$modelRequest->Id = $idSerie;
		$modelRequest->Locale = 0;
	
		$modelRequest->LanguageCode = '';
		$modelRequest->Country = $country;
	
		$response = $this->soapClient->LoadSeries($modelRequest);
	
		if(isset($response))
			return simplexml_load_string($response->LoadSeriesResult->any);
			
		return null;
	}
	
	function SearchDiscTitleByTitle($title = '', $country = '')
	{

		$modelRequest = new SearchDiscTitleByTitleRequest();
		$modelRequest->Title = $title;
		$modelRequest->Results = 10;
		$modelRequest->Strict = true;
		$modelRequest->IncludeEnglish = true;
		$modelRequest->IncludeAdult = true;
		$modelRequest->Country = $country;
		$modelRequest->Locale = 0;
		
		$response = $this->soapClient->SearchDiscTitleByTitle($modelRequest);
		
		if(isset($response))
			return simplexml_load_string($response->SearchDiscTitleByTitleResult->any);
		
		return null;
	
	}
	
}


