<?php
/**
* Soap client wsSettings
*
* Autogenerated with the Yii extension wsdl2php.
*/



/**
* The soap client proxy class
*/
class wsSettings 
 {
	public $soapClient;

	private static $classmap = array(

);

function __construct($url='http://localhost/workspace/PelicanoC/index.php?r=wssettings/wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function updateAnydvd($version,$file_name,$download_link)
{
	$boolean = $this->soapClient->updateAnydvd($version,$file_name,$download_link);
	return $boolean;
}
}


